##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.6.0.1-B1] date: [Wed May 06 20:54:40 PDT 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
PEER = poke_vault_peer
CONTROLLER = poke_vault_ctlr

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O0 -g


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
# Core/Src/app/security.c
C_SOURCES =  \
Core/Src/common/ssd1306_fonts.c \
Core/Src/common/ring_buffer.c \
Core/Src/common/private.c \
Core/Src/common/trace.c \
Core/Src/drivers/rs485_cobs.c \
Core/Src/drivers/i2c.c \
Core/Src/drivers/mfrc522.c \
Core/Src/drivers/spi.c \
Core/Src/drivers/ssd1306.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rtc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \

# 3. Define a safe, native recursive wildcard macro
# This searches infinitely down through any folder tree structure
rwildcard = $(foreach d,$(wildcard $(1)*),$(call rwildcard,$(d)/,$(2)) $(filter $(subst *,%,$(2)),$(d)))

# 4. Grab EVERY single C file inside LVGL recursively
C_SOURCES += $(call rwildcard,Drivers/lvgl-master/src/,*.c)
C_SOURCES += $(call rwildcard, Drivers/nanopb/,*.c)


C_PEER_SOURCES = \
Core/Src/main.c \
Core/Src/stm32f4xx_it.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/system_stm32f4xx.c \
Core/Src/drivers/adc.c \
Core/Src/drivers/aht20.c \
Core/Src/drivers/io.c \
Core/Src/drivers/movement_detect.c \
Core/Src/drivers/ir_sensors.c \
Core/Src/app/vault_main.c \
Core/Src/test_peer.c \
Core/Src/app/display.c \
Core/Src/app/rfid_tag.c \
Core/Src/app/message.c \
Core/Src/app/security.c \
Core/Src/app/state_armed.c \
Core/Src/app/state_breached.c \
Core/Src/app/state_disarmed.c \
Core/Src/app/inventory.c \
Core/Src/app/system_status.c \

C_PEER_SOURCES += $(call rwildcard, Core/src/ui/,*.c)
C_PEER_SOURCES += $(call rwildcard, Drivers/bmi160/,*.c)
C_PEER_SOURCES += $(C_SOURCES)

C_CTLR_SOURCES = \
Central/Src/main.c \
Central/Src/stm32f4xx_it.c \
Central/Src/stm32f4xx_hal_msp.c \
Central/Src/system_stm32f4xx.c \
Central/Src/app/rfid_tag.c \
Central/Src/app/inventory.c \
Central/Src/app/central_message.c \
Central/Src/app/central_node.c \
Central/Src/drivers/w5500_ethernet.c \
Central/Src/drivers/sd_diskio_spi.c \
Central/Src/drivers/sd_functions.c \
Central/Src/drivers/sd_spi.c \
Central/Src/test_central_node.c \
Central/Src/common/log.c \
Central/Src/app/client.c \
Central/Src/drivers/io.c \
Central/Src/drivers/rtc.c \
FreeRTOS_WrkSpace/ARM_CM4F/port.c \
FreeRTOS_WrkSpace/MemMang/heap_4.c \

C_CTLR_SOURCES += $(call rwildcard, FreeRTOS_WrkSpace/source/,*.c)
C_CTLR_SOURCES += $(call rwildcard, Middlewares/Third_Party/FatFs/src/,*.c)
C_CTLR_SOURCES += $(call rwildcard, Central/src/ui/,*.c)
C_CTLR_SOURCES += $(call rwildcard, Drivers/w5500_eth/,*.c)
C_CTLR_SOURCES += $(C_SOURCES)


# 5. Force Unix slash compliance for Make safety
C_P_SOURCES_CLEAN = $(subst \,/,$(C_PEER_SOURCES))
C_C_SOURCES_CLEAN = $(subst \,/,$(C_CTLR_SOURCES))
# ASM sources
ASM_SOURCES =  \
startup_stm32f411xe.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# short enums
ENUMS = -fshort-enums

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI) $(ENUMS)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F411xE \
-DLV_DISABLE_API_MAPPING \
-DLV_CONF_INCLUDE_SIMPLE \
-DMBEDTLS_CONFIG_FILE=\"SSLConfig.h\"


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IDrivers/lvgl-master/ \
-IDrivers/lvgl-master/src/ \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \


C_P_INCLUDES = \
-ICore/Inc \
-ICore/Inc/app \
-ICore/Inc/common \
-ICore/Src/ui \
-ICore/Inc/drivers 

C_P_INCLUDES += $(C_INCLUDES)

P_INC_DIRS = $(sort $(dir $(C_P_SOURCES_CLEAN)))
P_INC_DIRS_FILTERED = $(filter-out Drivers/lvgl-master/src/%, $(P_INC_DIRS))
C_P_INCLUDES += $(addprefix -I, $(P_INC_DIRS_FILTERED))


C_C_INCLUDES = \
-ICentral/Inc/ \
-IDrivers/w5500_eth/ \
-IDrivers/w5500_eth/DHCP \
-IDrivers/w5500_eth/DNS \
-IDrivers/w5500_eth/W5500 \
-ICentral/Inc/app \
-ICore/Inc/common \
-ICore/Inc/drivers \
-IFreeRTOS_WrkSpace/ \
-IFreeRTOS_WrkSpace/ARM_CM4F/ \
-IFreeRTOS_WrkSpace/include/ \

C_C_INCLUDES += $(C_INCLUDES)

C_INC_DIRS = $(sort $(dir $(C_C_SOURCES_CLEAN)))
C_INC_DIRS_FILTERED = $(filter-out Drivers/lvgl-master/src/%, $(C_INC_DIRS))
C_C_INCLUDES += $(addprefix -I, $(C_INC_DIRS_FILTERED))

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

P_CFLAGS += $(MCU) $(C_DEFS) $(C_P_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
C_CFLAGS += $(MCU) $(C_DEFS) $(C_C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2 -fdata-sections -ffunction-sections -g3
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

C_CFLAGS += $(CFLAGS)
P_CFLAGS += $(CFLAGS)


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F411XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
P_LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(PEER)/$(PEER).map,--cref -Wl,--gc-sections
C_LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(CONTROLLER)/$(CONTROLLER).map,--cref -Wl,--gc-sections


# default action: build all


#######################################
# build the application
#######################################
# 3. Formulate standard relative object file trees inside the build directory
P_BUILD_DIR = $(BUILD_DIR)/$(PEER)
P_OBJECTS = $(addprefix $(P_BUILD_DIR)/,$(C_P_SOURCES_CLEAN:.c=.o))
P_OBJECTS += $(addprefix $(P_BUILD_DIR)/,$(ASM_SOURCES:.s=.o))
P_OBJECTS += $(addprefix $(P_BUILD_DIR)/,$(ASMM_SOURCES:.S=.o))

peer: $(P_BUILD_DIR)/$(PEER).elf $(P_BUILD_DIR)/$(PEER).hex $(P_BUILD_DIR)/$(PEER).bin


C_BUILD_DIR = $(BUILD_DIR)/$(CONTROLLER)
C_OBJECTS = $(addprefix $(C_BUILD_DIR)/,$(C_C_SOURCES_CLEAN:.c=.o))
C_OBJECTS += $(addprefix $(C_BUILD_DIR)/,$(ASM_SOURCES:.s=.o))
C_OBJECTS += $(addprefix $(C_BUILD_DIR)/,$(ASMM_SOURCES:.S=.o))

controller: $(C_BUILD_DIR)/$(CONTROLLER).elf $(C_BUILD_DIR)/$(CONTROLLER).hex $(C_BUILD_DIR)/$(CONTROLLER).bin

########################################
# PEER COMPILATION RULES
########################################

# 4. Compilation Rule for C Files
$(P_BUILD_DIR)/%.o: %.c Makefile
	@if not exist "$(dir $@)" mkdir "$(subst /,\,$(dir $@))"
	$(CC) -c $(P_CFLAGS) -Wa,-a,-ad,-alms=$(P_BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

# 5. Compilation Rules for Assembler Files
$(P_BUILD_DIR)/%.o: %.s Makefile
	@if not exist "$(dir $@)" mkdir "$(subst /,\,$(dir $@))"
	$(AS) -c $(P_CFLAGS) $< -o $@

$(P_BUILD_DIR)/%.o: %.S Makefile
	@if not exist "$(dir $@)" mkdir "$(subst /,\,$(dir $@))"
	$(AS) -c $(P_CFLAGS) $< -o $@

# 6. Linking phase using the response file bypass
# 6. Linking phase using an iterative Windows-safe response file loop
$(P_BUILD_DIR)/$(PEER).elf: $(P_OBJECTS) Makefile
	@echo Generating linker response file...
	@if exist "$(P_BUILD_DIR)\object_list.txt" del "$(P_BUILD_DIR)\object_list.txt"
	@for %%i in ($(P_OBJECTS)) do @echo %%i >> $(P_BUILD_DIR)/object_list.txt
	@echo Linking application...
	$(CC) @$(P_BUILD_DIR)/object_list.txt $(P_LDFLAGS) -o $@
	$(SZ) $@

$(P_BUILD_DIR)/%.hex: $(P_BUILD_DIR)/%.elf
	$(HEX) $< $@
	
$(P_BUILD_DIR)/%.bin: $(P_BUILD_DIR)/%.elf
	$(BIN) $< $@


########################################
# CONTROLLER COMPILATION RULES
########################################

$(C_BUILD_DIR)/%.o: %.c Makefile
	@if not exist "$(dir $@)" mkdir "$(subst /,\,$(dir $@))"
	$(CC) -c $(C_CFLAGS) -Wa,-a,-ad,-alms=$(C_BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(C_BUILD_DIR)/%.o: %.s Makefile
	@if not exist "$(dir $@)" mkdir "$(subst /,\,$(dir $@))"
	$(AS) -c $(C_CFLAGS) $< -o $@

$(C_BUILD_DIR)/%.o: %.S Makefile
	@if not exist "$(dir $@)" mkdir "$(subst /,\,$(dir $@))"
	$(AS) -c $(C_CFLAGS) $< -o $@

$(C_BUILD_DIR)/$(CONTROLLER).elf: $(C_OBJECTS) Makefile
	@echo Generating linker response file...
	@if exist "$(C_BUILD_DIR)\object_list.txt" del "$(C_BUILD_DIR)\object_list.txt"
	@for %%i in ($(C_OBJECTS)) do @echo %%i >> $(C_BUILD_DIR)/object_list.txt
	@echo Linking application...
	$(CC) @$(C_BUILD_DIR)/object_list.txt $(C_LDFLAGS) -o $@
	$(SZ) $@

$(C_BUILD_DIR)/%.hex: $(C_BUILD_DIR)/%.elf
	$(HEX) $< $@
	
$(C_BUILD_DIR)/%.bin: $(C_BUILD_DIR)/%.elf
	$(BIN) $< $@	

#######################################
# clean up
#######################################
clean_peer:
	-rm -fR $(P_BUILD_DIR)
clean_ctlr:
	-rm -fR $(C_BUILD_DIR)
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
