#include "security.h"
#include "rfid_tag.h"


#define HAS_INTERNAL_EVT(sec_sm) (sec_sm->internal_event != EVENT_NONE)
#define NUM_TRANSITIONS (27U)

/************************
 * STATIC DECLARATIONS
 ************************/
typedef struct {
    state_e from;
    event_e event;
    state_e to;
}transition_t;

static transition_t transitions[NUM_TRANSITIONS] = {
    {SECURITY_ARMED, EVENT_NONE, SECURITY_ARMED},
    {SECURITY_ARMED, EVENT_TAG_AUTH, SECURITY_DISARMED},
    {SECURITY_ARMED, EVENT_REMOTE_AUTH, SECURITY_DISARMED},
    {SECURITY_ARMED, EVENT_UNIT_CLOSED, SECURITY_ARMED},
    {SECURITY_ARMED, EVENT_UNIT_OPENED, SECURITY_BREACHED},
    {SECURITY_ARMED, EVENT_UNIT_MOVED, SECURITY_BREACHED},
    {SECURITY_ARMED, EVENT_ITEM_SCAN, SECURITY_ARMED},

    {SECURITY_BREACHED, EVENT_NONE, SECURITY_BREACHED},
    {SECURITY_BREACHED, EVENT_TAG_AUTH, SECURITY_DISARMED},
    {SECURITY_BREACHED, EVENT_REMOTE_AUTH, SECURITY_DISARMED},
    {SECURITY_BREACHED, EVENT_UNIT_CLOSED, SECURITY_BREACHED},
    {SECURITY_BREACHED, EVENT_UNIT_OPENED, SECURITY_BREACHED},
    {SECURITY_BREACHED, EVENT_UNIT_MOVED, SECURITY_BREACHED},
    {SECURITY_BREACHED, EVENT_ITEM_SCAN, SECURITY_BREACHED},

    {SECURITY_DISARMED, EVENT_NONE, SECURITY_DISARMED},
    {SECURITY_DISARMED, EVENT_TAG_AUTH, SECURITY_DISARMED},
    {SECURITY_DISARMED, EVENT_REMOTE_AUTH, SECURITY_DISARMED},
    {SECURITY_DISARMED, EVENT_UNIT_CLOSED, SECURITY_ARMED},
    {SECURITY_DISARMED, EVENT_UNIT_OPENED, SECURITY_DISARMED},
    {SECURITY_DISARMED, EVENT_UNIT_MOVED, SECURITY_DISARMED},
    {SECURITY_DISARMED, EVENT_ITEM_SCAN, SECURITY_DISARMED},
};


static void state_enter(security_sm_t *sec_sm, transition_t trans);
static state_e security_process_event(security_sm_t *sec_sm, event_e event);
static event_e security_check_inputs(security_sm_t *sec_sm);
/***********************
 * PUBLIC APIs
 *****************/
/**
 * @brief Initializes the security module and necessary submodules
 * 
 * This API intializes the keycard and line_break submodules that 
 * make up the systems security mechanisms.
 */
void security_init(security_sm_t *sec_sm) {
    sec_sm->current_state = SECURITY_ARMED;
    sec_sm->common.sec_sm_data = sec_sm;
    sec_sm->common.sys_sens_status.presence = FALSE;
    sec_sm->common.sys_sens_status.no_presence = TRUE;
    sec_sm->common.sys_sens_status.unit_opened = FALSE;
    sec_sm->common.sys_sens_status.unit_closed = TRUE;
    sec_sm->common.sys_sens_status.unit_movement.motion_detected = FALSE;
    sec_sm->common.sys_sens_status.unit_movement.tap_detected = FALSE;
    sec_sm->common.sys_sens_status.temp_hum_readings.humidity = 0;
    sec_sm->common.sys_sens_status.temp_hum_readings.temp = 0;

    sec_sm->armed.comm = sec_sm;
    sec_sm->breached.comm = sec_sm;
    sec_sm->disarmed.comm = sec_sm;

    disarmed_state_init(&sec_sm->disarmed);
    armed_state_init(&sec_sm->armed);
    breached_state_init(&sec_sm->breached);
}


/**
 * @brief Posts the specified event to the security SM
 * 
 * 
 * Problem with this approach is that we need a way to pass 
 * the data associated with an event from the outside...
 * 
 * @param[in] event event to post to the SM
 */
uint8_t security_post_event(security_sm_t* sec_sm, event_e event) {
    uint8_t status = STATUS_ERR;

    if (!HAS_INTERNAL_EVT(sec_sm)) {
        sec_sm->internal_event = event;
        status = STATUS_OK;
    }

    return status;
}



/**
 * @brief Process system event generator by sensor inputs
 * 
 * 
 * This function processes events generated by sensor inputs
 * updating security state accordingly. Runs to completion and must
 * be called until event_processed is set to true.
 * 
 * @param[in] sec_sm current statemachine struct
 * @param[out] event_processed indicates whether the current event has 
 * been processed to completion
 * 
 * @return returns the current state of the security system
 */
state_e security_run(security_sm_t *sec_sm, uint8_t *event_processed) {
    event_e event = security_check_inputs(sec_sm);
    return security_process_event(sec_sm, event);
}


/********************
 * STATIC DECLARATIONS
 **********************/

static void state_enter(security_sm_t *sec_sm, transition_t trans) {
    if (sec_sm->current_state != trans.to)
        sec_sm->current_state = trans.to;
    
    switch (trans.to) {
    case SECURITY_ARMED:
        armed_state_enter(&sec_sm->armed, trans.from, trans.event);
        break;
    case SECURITY_DISARMED:
        disarmed_state_enter(&sec_sm->disarmed, trans.from, trans.event);
        break;
    case SECURITY_BREACHED:
        breached_state_enter(&sec_sm->breached, trans.from, trans.event);
        break;
    }
}


/**
 * @brief Updates the current security state based on the current readings
 */
static state_e security_process_event(security_sm_t *sec_sm, event_e event) {
    state_e curr_state = sec_sm->current_state;

    for (uint8_t i = 0; i < NUM_TRANSITIONS; ++i) {
        if (curr_state == transitions[i].from && event == transitions[i].event) {
            state_enter(sec_sm, transitions[i]);
            curr_state = transitions[i].to;
            break;
        }
    }

    return curr_state;
}


/**
 * @brief Retrieves the current security state
 * 
 * This API queries the security components, e.g. 
 * MFRC522 card status, line break status, etc. Compares the 
 * result of these queries and returns the state of 
 * the security system depending on the combination of 
 * values.
 */
static event_e security_check_inputs(security_sm_t *sec_sm) {
    event_e event = EVENT_NONE;
    system_retrieve_state(&sec_sm->common.sys_sens_status);

    // events processed in order of importance
    if (HAS_INTERNAL_EVT(sec_sm))
        event = take_internal_event(sec_sm);
    else if (sec_sm->common.sys_sens_status.unit_opened)
        event = EVENT_UNIT_OPENED;
    else if (sec_sm->common.sys_sens_status.unit_movement.motion_detected)
        event = EVENT_UNIT_MOVED;
    else if (sec_sm->common.sys_sens_status.unit_closed)
        event = EVENT_UNIT_CLOSED;

    return event;
}


/**
 * @brief Take an internal event when present
 * 
 * 
 */
static event_e take_internal_event(security_sm_t *sec_sm) {
    uint8_t event = sec_sm->internal_event;
    sec_sm->internal_event = EVENT_NONE;
    return event;
}

