syntax = "proto2";

message msg_array {
    repeated msg msgs = 1;
}

message msg {
    required uint32 command = 1;
    required uint32 node_id = 2;

    oneof payload {
        alert type_alert = 3;
        transaction type_transaction = 4;
        event type_event = 5;
    }
}

message alert {
    required uint32 type = 1;
    required uint32 value = 2;
}


message transaction {
    required string item_name = 1;
    required string item_cond = 2;
}


message event {
    required uint32 type = 1;
    required uint32 value = 2;
}

