/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "../../Drivers/nanopb/messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(msg_array, msg_array, AUTO)


PB_BIND(msg, msg, AUTO)


PB_BIND(alert, alert, AUTO)


PB_BIND(transaction, transaction, AUTO)


PB_BIND(event, event, AUTO)



