/**
 * This module utilizes the IR sensors and MFRC522
 * RFID reader to implement the security mechanism of 
 * the system.
 */
#ifndef _SECURITY_H
#define _SECURITY_H

#include "../drivers/ir_sensors.h"
#include "./rfid_tag.h"
#include "state_common.h"
#include "state_armed.h"
#include "state_breached.h"
#include "state_disarmed.h"

/******************
 * ENUMS/STRUCTS
 *****************/


typedef struct {
    state_e current_state;
    struct state_common_data common;
    struct state_armed_data armed;
    struct state_disarmed_data disarmed;
    struct state_breached_data breached;

    event_e internal_event;
} security_sm_t;

/*****************
 * USER APIs
 *****************/


/**
 * @brief Initializes the security module and necessary submodules
 * 
 * This API intializes the keycard and line_break submodules that 
 * make up the systems security mechanisms.
 */
void security_init(security_sm_t *);



/**
 * @brief Process system event generator by sensor inputs
 * 
 * 
 * This function processes events generated by sensor inputs
 * updating security state accordingly. Runs to completion and must
 * be called until event_processed is set to true.
 * 
 * @param[out] event_processed indicates whether the current event has 
 * been processed to completion
 * 
 * @return returns the current state of the security system
 */
state_e security_run(security_sm_t *sec_sm, uint8_t *event_processed);



/**
 * @brief Posts the specified event to the security SM
 * 
 * 
 * Problem with this approach is that we need a way to pass 
 * the data associated with an event from the outside...
 * 
 * @param[in] event event to post to the SM
 */
uint8_t security_post_event(security_sm_t* sec_sm, event_e event);


#endif